# Generated by Django 5.0.6 on 2024-09-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_categories', '0002_alter_budget_categories_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_categories',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
