# Generated by Django 5.0.6 on 2024-08-04 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_budget_categories_junction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbudgetcategoryjunction',
            old_name='budget_category',
            new_name='budget_category_id',
        ),
        migrations.RenameField(
            model_name='userbudgetcategoryjunction',
            old_name='user',
            new_name='userId',
        ),
    ]
