# Generated by Django 5.0.6 on 2024-09-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_budget_categories_junction', '0002_rename_budget_category_userbudgetcategoryjunction_budget_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbudgetcategoryjunction',
            old_name='userId',
            new_name='user',
        ),
    ]
