# Generated by Django 5.0.6 on 2024-09-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='userId',
            new_name='user',
        ),
    ]
