# Generated by Django 5.0.6 on 2024-09-22 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_categories', '0003_budget_categories_is_custom'),
        ('transactions', '0004_alter_transaction_transactiontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transactionType',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget_categories.budget_categories'),
        ),
    ]
