# Generated by Django 5.0.6 on 2024-10-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_transaction_transactiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10, null=True),
        ),
    ]
