# Generated by Django 5.0.6 on 2025-05-15 07:39

import transactions.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_transactiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionAmount',
            field=transactions.models.EncryptedDecimalField(decimal_places=2, max_digits=20),
        ),
    ]
